:Date: 07/04/2020
:Author: Ben Martinez-Bateman
:Email: ben@murmurcreative.com
:toc: macro
:toclevels: 3
:toc-title:
:sectanchors:
:sectlinks:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:tip-caption: 💡
:note-caption: ℹ
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠
endif::[]

= Drawer

*Broadly:* Open things and close them as well.

*Technically:* Swap states on a particular element.

toc::[]

== Using It

First, create an element to be your drawer:

[source,html]
----
<div data-module="drawer">
    <!--  Clothes, cables, etc  -->
</div>
----

Next, import Drawer and start it up:

[source,javascript]
----
import {Cabinet} from 'murmur-drawer';

new Cabinet();
----

Now you have a Drawer!

Unfortunately it won't look like much, so please take a look at the link:#config[configuration] and link:#api[API] sections.

[#config]
== Configuration

Both `Drawer` and `Cabinet` take a second argument that can contain more specific settings.
Passing an object to this argument will overwrite the defaults on a per-property basis.
This is done using a shallow merge.

[horizontal]
`states`:: *Default:* `['closed', 'open']`
+
An array of strings.
These are the states that appear in `data-state`.
`cycle()` will move through them in order, one at a time, looping to the beginning once last row is reached.
The strings themselves are essentially arbitrary.
`initState`:: *Default:* `undefined` (effectively `states[0]`)
+
The initial state.
Must be a string from `states`.
If nothing is defined here, then the first state in `states` will be used.
+
Can be overridden by adding `data-state="state-name"` to the Drawer HTML.
`hiddenStates`:: *Default:* `['closed']`
+
An array of strings.
When the Drawer is in a state listed here, it will be considered hidden and the `hidden` HTML attribute will be applied.
If you don't ever want the drawer to be hidden, just set this to an empty array.
`actions`:: *Default:* `[]`
+
An array of callbacks, called when the Drawer observes its state changing.
See link:#api[`addAction()`] for details on how to define actions.
`knobs`:: *Default:* `[]`
+
An array of elements or selectors that will be attached to this Drawer.
+
Can be overridden by adding `data-knob="selector"` to the Drawer HTML.
`knobsCycle`:: *Default:* `true`
+
A boolean that determines whether or not clicking on a Knob will fire `cycle()` on its attached Drawers.
`knobActions`:: *Default:* `[]`
+
An array of callbacks, called when a Knob observes a state change on an attached Drawer.
Callbacks receive arguments that are the mutation list, Knob DOM element, and Knob observer.

[#instantiation]
== Instantiation

- `new Drawer(element, settings)` - The `element` argument is *required* and _must_ be a reference to a DOM element, i.e. the result of `document.querySelector()`.
Use this if you want to instantiate only a single, specific Drawer
(i.e. a site navigation menu).
+
This returns an API object (see below) for the Drawer.
- `new Cabinet(selector, settings)` - The `selector` argument is *required*, and must be either a valid selector
(i.e. something `document.querySelectorAll()` understands)
or a reference to a DOM element.
Use this if you want to instantiate a bunch of Drawers at once with the same settings
(i.e. an accordion).
+
This returns an array of API objects (see below).

[#api]
== API

Each Drawer has an API object that contains settings information as well as several methods for interacting with that Drawer.

These API objects are returned by link:#instantiation[`new Drawer()` and `new Cabinet()`], and can also be found attached to the Drawer element, under the `drawer` property.

[horizontal]
`settings`:: Contains information describing Drawer behavior.
See link:#config[Config] for full settings documentation.
`getState()`:: Returns the current state of the Drawer.
`setState(state)`:: Sets the state of the Drawer.
`setHidden(hide)`:: Sets the `hidden` attribute of the Drawer element.
`addKnob(knob)`:: Adds a link:#knobs[Knob].
`cycle(states)`:: Advances the Drawer through states.
If the `states` argument is undefined/not passed, then it will move to the next state defined in settings.
If the `states` argument is an array of valid states
(that is, states that also appear in the settings)
then it will move to the next valid state in that array.
See the link:src/drawer.js[function definition] for more information.
`addAction(action)`:: Add a callback that will be called when the Drawer detects a state change.
The callback recieves the following arguments:
** `list` - An array of mutations detected.
** `el` - The DOM element of the Drawer.
** `observer` - The observer that is watching this drawer.

[#knobs]
== Knobs

Knobs are elements that become attached to a Drawer:
More specifically, they observe the Drawer with MutationObserver in the same way it observes itself, and fire their own actions when they detect mutations.
By default, when clicks Knobs will cycle a Drawer through its states.

Your Drawers aren't required to have Knobs, but they are a quick and easy way to implement the functionality 80% of Drawers are deployed for.

You can attach a Knob to a Drawer in one of three ways:

. Provide an element or selector in the settings at instantiation:
+
[source,javascript]
----
new Drawer(`.drawer`, {knobs: [`.knob`]})
----

. Use `addKnob` to add a Knob to an already instantiated Drawer:
+
[source,javascript]
----
(new Drawer(`.drawer`)).addKnob(`.knob`);

// or

const {addKnob} = document.querySelector(`drawer`).drawer;
addKnob(`.knob`);
----

. Provide a selector in the `data-knob` attribute:
+
[source,html]
----
<div class="drawer" data-knob=".knob"> ... </div>
----

[IMPORTANT]
====
A Drawer can have multiple Knobs, and methods 1 and 3 above can result in attaching multiple Knobs if the provided selectors match more than on element in the DOM.
====

The following is a simple, complete example that will result in a drawer that can be opened and closed by clicking on the button:

[source,javascript]
----
import {Drawer} from "murmur-drawer";

new Drawer(document.querySelector(`.drawer`));
----

[source,html]
----
<div class="drawer"
    data-knob="button[data-controls='drawer']"> 🧦🧦🧦🧦🧦🧦🧦🧦 </div>
<button data-controls="drawer"> Toggle </button>
----

== Further Reading
Drawer is several dozen lines of code that manage, essentially, one thing:

[source,html]
----
data-state="open"
----

This is the single source of truth for everything Drawer does, and by taking advantage of a number of native browser features it does so efficiently and extensibly.

Using link:https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver[MutationObserver], Drawer watches for state changes and reacts to them.
You are of course encouraged to use Drawer's simple API to interact with its state, but the beauty of MutationObserver is that it doesn't matter:

[source,javascript]
----
const el = document.querySelector(`.drawer`);

// Drawer API
const {setState} = el.drawer;
setState(`closed`);

// Direct access
drawer.dataset.state = `closed`;
----


== Goals

=== Better IE11 Compatibility

Trying to get v1 of this module to work with IE11 was possible, but a huge hassle.
By avoiding any framework, and keeping the source simple, my intent is to make v2 either compatible out of the box, or compatible with a minimal amount of work.
This might look like distributing a separate transpiled source file for browsers that don't support modern technologies, or a sort section in the Readme detailing how to get it working in IE11.

Whatever the case, you should be able to trust that this module will work, easily, in IE11.

=== Simpler

Instead of getting fancy with things like web components, this keeps it simple:
No frameworks or dependencies, just good old link:http://vanilla-js.com/[Vanilla JS].
